// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teaicfxjreenkbqiczwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYWljZnhqcmVlbmticWljendtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTQ0NTEsImV4cCI6MjA2NzQzMDQ1MX0.2uMPm_PNY2SwxPrqv14oD6LimK36cCmr-NvB2q5zr4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});